#!/bin/sh
set -x
./clean.sh
mkdir -p CODE/FRAMEWORK/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/CONTROLLER/connect_user_controller.phx CODE/ADMINISTRATION/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/CONTROLLER/controller.phx CODE/ADMINISTRATION/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/CONTROLLER/disconnect_user_controller.phx CODE/ADMINISTRATION/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/CONTROLLER/do_connect_user_controller.phx CODE/ADMINISTRATION/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/CONTROLLER/show_error_controller.phx CODE/ADMINISTRATION/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/CONTROLLER/upload_file_controller.phx CODE/ADMINISTRATION/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/CONTROLLER/upload_image_controller.phx CODE/ADMINISTRATION/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/CONTROLLER/upload_video_controller.phx CODE/ADMINISTRATION/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/STYLE/base_style.styl CODE/ADMINISTRATION/STYLE/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/VIEW/connect_user_view.pht CODE/ADMINISTRATION/VIEW/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/VIEW/show_error_view.pht CODE/ADMINISTRATION/VIEW/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/VIEW/BLOCK/page_body_block.pht CODE/ADMINISTRATION/VIEW/BLOCK/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/VIEW/BLOCK/page_footer_block.pht CODE/ADMINISTRATION/VIEW/BLOCK/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/ADMINISTRATION/VIEW/BLOCK/page_head_block.pht CODE/ADMINISTRATION/VIEW/BLOCK/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/CONTROLLER/add_contact_controller.phx CODE/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/CONTROLLER/connect_user_controller.phx CODE/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/CONTROLLER/controller.phx CODE/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/CONTROLLER/disconnect_user_controller.phx CODE/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/CONTROLLER/get_captcha_image_controller.phx CODE/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/CONTROLLER/view_controller.phx CODE/CONTROLLER/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/FRAMEWORK/*.* CODE/FRAMEWORK/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/MODEL/contact.phx CODE/MODEL/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/MODEL/contact_model.phx CODE/MODEL/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/MODEL/session.phx CODE/MODEL/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/MODEL/text.phx CODE/MODEL/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/MODEL/text_model.phx CODE/MODEL/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/MODEL/user.phx CODE/MODEL/
cp ../../../TOOL/PHOENIX/SAMPLE/CODE/MODEL/user_model.phx CODE/MODEL/
cp ../../../TOOL/PHOENIX/SAMPLE/DATABASE/administration.bt DATABASE/
cp ../../../TOOL/PHOENIX/SAMPLE/DATABASE/api.bt DATABASE/
mkdir -p CODE/STYLE/VISTA/
cp ../../../TOOL/VISTA/CODE/STYLUS/*.* CODE/STYLE/VISTA/
mkdir -p www/static/script/
cp ../../../TOOL/VISTA/CODE/JAVASCRIPT/*.* www/static/script/
